/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as commonRouteRouteImport } from './routes/(common)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as commonIndexRouteImport } from './routes/(common)/index'
import { Route as commonRealGoodRouteImport } from './routes/(common)/real-good'
import { Route as commonProfileCardRouteImport } from './routes/(common)/profile-card'
import { Route as commonP24IndexRouteImport } from './routes/(common)/p24/index'
import { Route as commonHelloIndexRouteImport } from './routes/(common)/hello/index'
import { Route as commonDrawIndexRouteImport } from './routes/(common)/draw/index'
import { Route as authenticatedChatIndexRouteImport } from './routes/(authenticated)/chat/index'
import { Route as authenticatedAgentIndexRouteImport } from './routes/(authenticated)/agent/index'
import { Route as commonHelloRoomIdRouteImport } from './routes/(common)/hello/$roomId'
import { Route as authenticatedChatRoomIdRouteImport } from './routes/(authenticated)/chat/$roomId'
import { Route as authenticatedAgentChatIdRouteImport } from './routes/(authenticated)/agent/$chatId'

const commonRouteRoute = commonRouteRouteImport.update({
  id: '/(common)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const commonIndexRoute = commonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => commonRouteRoute,
} as any)
const commonRealGoodRoute = commonRealGoodRouteImport.update({
  id: '/real-good',
  path: '/real-good',
  getParentRoute: () => commonRouteRoute,
} as any)
const commonProfileCardRoute = commonProfileCardRouteImport.update({
  id: '/profile-card',
  path: '/profile-card',
  getParentRoute: () => commonRouteRoute,
} as any)
const commonP24IndexRoute = commonP24IndexRouteImport.update({
  id: '/p24/',
  path: '/p24/',
  getParentRoute: () => commonRouteRoute,
} as any)
const commonHelloIndexRoute = commonHelloIndexRouteImport.update({
  id: '/hello/',
  path: '/hello/',
  getParentRoute: () => commonRouteRoute,
} as any)
const commonDrawIndexRoute = commonDrawIndexRouteImport.update({
  id: '/draw/',
  path: '/draw/',
  getParentRoute: () => commonRouteRoute,
} as any)
const authenticatedChatIndexRoute = authenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAgentIndexRoute = authenticatedAgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const commonHelloRoomIdRoute = commonHelloRoomIdRouteImport.update({
  id: '/hello/$roomId',
  path: '/hello/$roomId',
  getParentRoute: () => commonRouteRoute,
} as any)
const authenticatedChatRoomIdRoute = authenticatedChatRoomIdRouteImport.update({
  id: '/chat/$roomId',
  path: '/chat/$roomId',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAgentChatIdRoute =
  authenticatedAgentChatIdRouteImport.update({
    id: '/agent/$chatId',
    path: '/agent/$chatId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/profile-card': typeof commonProfileCardRoute
  '/real-good': typeof commonRealGoodRoute
  '/': typeof commonIndexRoute
  '/agent/$chatId': typeof authenticatedAgentChatIdRoute
  '/chat/$roomId': typeof authenticatedChatRoomIdRoute
  '/hello/$roomId': typeof commonHelloRoomIdRoute
  '/agent/': typeof authenticatedAgentIndexRoute
  '/chat/': typeof authenticatedChatIndexRoute
  '/draw/': typeof commonDrawIndexRoute
  '/hello/': typeof commonHelloIndexRoute
  '/p24/': typeof commonP24IndexRoute
}
export interface FileRoutesByTo {
  '/profile-card': typeof commonProfileCardRoute
  '/real-good': typeof commonRealGoodRoute
  '/': typeof commonIndexRoute
  '/agent/$chatId': typeof authenticatedAgentChatIdRoute
  '/chat/$roomId': typeof authenticatedChatRoomIdRoute
  '/hello/$roomId': typeof commonHelloRoomIdRoute
  '/agent': typeof authenticatedAgentIndexRoute
  '/chat': typeof authenticatedChatIndexRoute
  '/draw': typeof commonDrawIndexRoute
  '/hello': typeof commonHelloIndexRoute
  '/p24': typeof commonP24IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(common)': typeof commonRouteRouteWithChildren
  '/(common)/profile-card': typeof commonProfileCardRoute
  '/(common)/real-good': typeof commonRealGoodRoute
  '/(common)/': typeof commonIndexRoute
  '/(authenticated)/agent/$chatId': typeof authenticatedAgentChatIdRoute
  '/(authenticated)/chat/$roomId': typeof authenticatedChatRoomIdRoute
  '/(common)/hello/$roomId': typeof commonHelloRoomIdRoute
  '/(authenticated)/agent/': typeof authenticatedAgentIndexRoute
  '/(authenticated)/chat/': typeof authenticatedChatIndexRoute
  '/(common)/draw/': typeof commonDrawIndexRoute
  '/(common)/hello/': typeof commonHelloIndexRoute
  '/(common)/p24/': typeof commonP24IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile-card'
    | '/real-good'
    | '/'
    | '/agent/$chatId'
    | '/chat/$roomId'
    | '/hello/$roomId'
    | '/agent/'
    | '/chat/'
    | '/draw/'
    | '/hello/'
    | '/p24/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile-card'
    | '/real-good'
    | '/'
    | '/agent/$chatId'
    | '/chat/$roomId'
    | '/hello/$roomId'
    | '/agent'
    | '/chat'
    | '/draw'
    | '/hello'
    | '/p24'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(common)'
    | '/(common)/profile-card'
    | '/(common)/real-good'
    | '/(common)/'
    | '/(authenticated)/agent/$chatId'
    | '/(authenticated)/chat/$roomId'
    | '/(common)/hello/$roomId'
    | '/(authenticated)/agent/'
    | '/(authenticated)/chat/'
    | '/(common)/draw/'
    | '/(common)/hello/'
    | '/(common)/p24/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  commonRouteRoute: typeof commonRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(common)': {
      id: '/(common)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof commonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(common)/': {
      id: '/(common)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof commonIndexRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(common)/real-good': {
      id: '/(common)/real-good'
      path: '/real-good'
      fullPath: '/real-good'
      preLoaderRoute: typeof commonRealGoodRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(common)/profile-card': {
      id: '/(common)/profile-card'
      path: '/profile-card'
      fullPath: '/profile-card'
      preLoaderRoute: typeof commonProfileCardRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(common)/p24/': {
      id: '/(common)/p24/'
      path: '/p24'
      fullPath: '/p24/'
      preLoaderRoute: typeof commonP24IndexRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(common)/hello/': {
      id: '/(common)/hello/'
      path: '/hello'
      fullPath: '/hello/'
      preLoaderRoute: typeof commonHelloIndexRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(common)/draw/': {
      id: '/(common)/draw/'
      path: '/draw'
      fullPath: '/draw/'
      preLoaderRoute: typeof commonDrawIndexRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(authenticated)/chat/': {
      id: '/(authenticated)/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof authenticatedChatIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/agent/': {
      id: '/(authenticated)/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof authenticatedAgentIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(common)/hello/$roomId': {
      id: '/(common)/hello/$roomId'
      path: '/hello/$roomId'
      fullPath: '/hello/$roomId'
      preLoaderRoute: typeof commonHelloRoomIdRouteImport
      parentRoute: typeof commonRouteRoute
    }
    '/(authenticated)/chat/$roomId': {
      id: '/(authenticated)/chat/$roomId'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof authenticatedChatRoomIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/agent/$chatId': {
      id: '/(authenticated)/agent/$chatId'
      path: '/agent/$chatId'
      fullPath: '/agent/$chatId'
      preLoaderRoute: typeof authenticatedAgentChatIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedAgentChatIdRoute: typeof authenticatedAgentChatIdRoute
  authenticatedChatRoomIdRoute: typeof authenticatedChatRoomIdRoute
  authenticatedAgentIndexRoute: typeof authenticatedAgentIndexRoute
  authenticatedChatIndexRoute: typeof authenticatedChatIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAgentChatIdRoute: authenticatedAgentChatIdRoute,
  authenticatedChatRoomIdRoute: authenticatedChatRoomIdRoute,
  authenticatedAgentIndexRoute: authenticatedAgentIndexRoute,
  authenticatedChatIndexRoute: authenticatedChatIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface commonRouteRouteChildren {
  commonProfileCardRoute: typeof commonProfileCardRoute
  commonRealGoodRoute: typeof commonRealGoodRoute
  commonIndexRoute: typeof commonIndexRoute
  commonHelloRoomIdRoute: typeof commonHelloRoomIdRoute
  commonDrawIndexRoute: typeof commonDrawIndexRoute
  commonHelloIndexRoute: typeof commonHelloIndexRoute
  commonP24IndexRoute: typeof commonP24IndexRoute
}

const commonRouteRouteChildren: commonRouteRouteChildren = {
  commonProfileCardRoute: commonProfileCardRoute,
  commonRealGoodRoute: commonRealGoodRoute,
  commonIndexRoute: commonIndexRoute,
  commonHelloRoomIdRoute: commonHelloRoomIdRoute,
  commonDrawIndexRoute: commonDrawIndexRoute,
  commonHelloIndexRoute: commonHelloIndexRoute,
  commonP24IndexRoute: commonP24IndexRoute,
}

const commonRouteRouteWithChildren = commonRouteRoute._addFileChildren(
  commonRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  commonRouteRoute: commonRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
