/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealGoodRouteImport } from './routes/real-good'
import { Route as ProfileCardRouteImport } from './routes/profile-card'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelloIndexRouteImport } from './routes/hello/index'
import { Route as HelloRoomIdRouteImport } from './routes/hello/$roomId'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'
import { Route as authenticatedChatRouteImport } from './routes/(authenticated)/chat'

const RealGoodRoute = RealGoodRouteImport.update({
  id: '/real-good',
  path: '/real-good',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCardRoute = ProfileCardRouteImport.update({
  id: '/profile-card',
  path: '/profile-card',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloIndexRoute = HelloIndexRouteImport.update({
  id: '/hello/',
  path: '/hello/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoomIdRoute = HelloRoomIdRouteImport.update({
  id: '/hello/$roomId',
  path: '/hello/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedChatRoute = authenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => authenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile-card': typeof ProfileCardRoute
  '/real-good': typeof RealGoodRoute
  '/chat': typeof authenticatedChatRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/hello/$roomId': typeof HelloRoomIdRoute
  '/hello': typeof HelloIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile-card': typeof ProfileCardRoute
  '/real-good': typeof RealGoodRoute
  '/chat': typeof authenticatedChatRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/hello/$roomId': typeof HelloRoomIdRoute
  '/hello': typeof HelloIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/profile-card': typeof ProfileCardRoute
  '/real-good': typeof RealGoodRoute
  '/(authenticated)/chat': typeof authenticatedChatRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/hello/$roomId': typeof HelloRoomIdRoute
  '/hello/': typeof HelloIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile-card'
    | '/real-good'
    | '/chat'
    | '/dashboard'
    | '/hello/$roomId'
    | '/hello'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile-card'
    | '/real-good'
    | '/chat'
    | '/dashboard'
    | '/hello/$roomId'
    | '/hello'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/profile-card'
    | '/real-good'
    | '/(authenticated)/chat'
    | '/(authenticated)/dashboard'
    | '/hello/$roomId'
    | '/hello/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  ProfileCardRoute: typeof ProfileCardRoute
  RealGoodRoute: typeof RealGoodRoute
  HelloRoomIdRoute: typeof HelloRoomIdRoute
  HelloIndexRoute: typeof HelloIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/real-good': {
      id: '/real-good'
      path: '/real-good'
      fullPath: '/real-good'
      preLoaderRoute: typeof RealGoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-card': {
      id: '/profile-card'
      path: '/profile-card'
      fullPath: '/profile-card'
      preLoaderRoute: typeof ProfileCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello/': {
      id: '/hello/'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello/$roomId': {
      id: '/hello/$roomId'
      path: '/hello/$roomId'
      fullPath: '/hello/$roomId'
      preLoaderRoute: typeof HelloRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/chat': {
      id: '/(authenticated)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof authenticatedChatRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedChatRoute: typeof authenticatedChatRoute
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedChatRoute: authenticatedChatRoute,
  authenticatedDashboardRoute: authenticatedDashboardRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  ProfileCardRoute: ProfileCardRoute,
  RealGoodRoute: RealGoodRoute,
  HelloRoomIdRoute: HelloRoomIdRoute,
  HelloIndexRoute: HelloIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
