/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealGoodRouteImport } from './routes/real-good'
import { Route as IndexRouteImport } from './routes/index'

const RealGoodRoute = RealGoodRouteImport.update({
  id: '/real-good',
  path: '/real-good',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/real-good': typeof RealGoodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/real-good': typeof RealGoodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/real-good': typeof RealGoodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/real-good'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/real-good'
  id: '__root__' | '/' | '/real-good'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RealGoodRoute: typeof RealGoodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/real-good': {
      id: '/real-good'
      path: '/real-good'
      fullPath: '/real-good'
      preLoaderRoute: typeof RealGoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RealGoodRoute: RealGoodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
